services:
  app:
    build: ./scripts/docker/app
    volumes:
      - ./src:/src
      - ./data:/data
  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
