"""add education levels table

Revision ID: 05ccfb61e7da
Revises: 5a06d85831d3
Create Date: 2021-01-03 20:35:58.486069

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "05ccfb61e7da"
down_revision = "5a06d85831d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "education_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("geo_code", sa.String(), nullable=True),
        sa.Column("geo_name", sa.String(), nullable=True),
        sa.Column("geo_level", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("no_diploma", sa.Integer(), nullable=True),
        sa.Column("secondary_school_diploma", sa.Integer(), nullable=True),
        sa.Column("apprenticeship_trades_diploma", sa.Integer(), nullable=True),
        sa.Column("college_diploma", sa.Integer(), nullable=True),
        sa.Column("university_diploma_below_bachelor", sa.Integer(), nullable=True),
        sa.Column("bachelor_degree", sa.Integer(), nullable=True),
        sa.Column("university_diploma_above_bachelor", sa.Integer(), nullable=True),
        sa.Column("medical_degree", sa.Integer(), nullable=True),
        sa.Column("masters_degree", sa.Integer(), nullable=True),
        sa.Column("earned_doctorate", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_education_levels_geo_code"),
        "education_levels",
        ["geo_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_education_levels_year"), "education_levels", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_education_levels_year"), table_name="education_levels")
    op.drop_index(op.f("ix_education_levels_geo_code"), table_name="education_levels")
    op.drop_table("education_levels")
    # ### end Alembic commands ###
