"""add age group table

Revision ID: 627d10c2ed63
Revises: 
Create Date: 2021-01-03 17:31:22.704439

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "627d10c2ed63"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "age_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("geo_code", sa.String(), nullable=True),
        sa.Column("geo_name", sa.String(), nullable=True),
        sa.Column("geo_level", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("age_0_to_4", sa.Integer(), nullable=True),
        sa.Column("age_5_to_9", sa.Integer(), nullable=True),
        sa.Column("age_10_to_14", sa.Integer(), nullable=True),
        sa.Column("age_15_to_19", sa.Integer(), nullable=True),
        sa.Column("age_20_to_24", sa.Integer(), nullable=True),
        sa.Column("age_25_to_29", sa.Integer(), nullable=True),
        sa.Column("age_30_to_34", sa.Integer(), nullable=True),
        sa.Column("age_35_to_39", sa.Integer(), nullable=True),
        sa.Column("age_40_to_44", sa.Integer(), nullable=True),
        sa.Column("age_45_to_49", sa.Integer(), nullable=True),
        sa.Column("age_50_to_54", sa.Integer(), nullable=True),
        sa.Column("age_55_to_59", sa.Integer(), nullable=True),
        sa.Column("age_60_to_64", sa.Integer(), nullable=True),
        sa.Column("age_65_to_69", sa.Integer(), nullable=True),
        sa.Column("age_70_to_74", sa.Integer(), nullable=True),
        sa.Column("age_75_to_79", sa.Integer(), nullable=True),
        sa.Column("age_80_to_84", sa.Integer(), nullable=True),
        sa.Column("age_85_plus", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_age_groups_geo_code"), "age_groups", ["geo_code"], unique=False
    )
    op.create_index(op.f("ix_age_groups_year"), "age_groups", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_age_groups_year"), table_name="age_groups")
    op.drop_index(op.f("ix_age_groups_geo_code"), table_name="age_groups")
    op.drop_table("age_groups")
    # ### end Alembic commands ###
