"""add age group table

Revision ID: b0fa08a278de
Revises: 
Create Date: 2021-01-03 08:10:20.099211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b0fa08a278de"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "age_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("geo_code", sa.String(), nullable=True),
        sa.Column("geo_name", sa.String(), nullable=True),
        sa.Column("geo_level", sa.Integer(), nullable=True),
        sa.Column("age_0_to_4", sa.Integer(), nullable=True),
        sa.Column("age_5_to_9", sa.Integer(), nullable=True),
        sa.Column("age_10_to_14", sa.Integer(), nullable=True),
        sa.Column("age_15_to_19", sa.Integer(), nullable=True),
        sa.Column("age_20_to_24", sa.Integer(), nullable=True),
        sa.Column("age_25_to_29", sa.Integer(), nullable=True),
        sa.Column("age_30_to_34", sa.Integer(), nullable=True),
        sa.Column("age_35_to_39", sa.Integer(), nullable=True),
        sa.Column("age_40_to_44", sa.Integer(), nullable=True),
        sa.Column("age_45_to_49", sa.Integer(), nullable=True),
        sa.Column("age_50_to_54", sa.Integer(), nullable=True),
        sa.Column("age_55_to_59", sa.Integer(), nullable=True),
        sa.Column("age_60_to_64", sa.Integer(), nullable=True),
        sa.Column("age_65_to_69", sa.Integer(), nullable=True),
        sa.Column("age_70_to_74", sa.Integer(), nullable=True),
        sa.Column("age_75_to_79", sa.Integer(), nullable=True),
        sa.Column("age_80_to_84", sa.Integer(), nullable=True),
        sa.Column("age_85_plus", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("age_groups")
    # ### end Alembic commands ###
